### ISSUE TITLE
Multiple UIDs (DB entries) for VODs

### ISSUE THREAD

**Issue by Clasko** [AgileProggers/archiv-backend#8]
I noticed that sometimes the same VOD is inserted into the DB with different UIDs:

Some examples:
<img width="1317" alt="CleanShot 2022-10-09 at 11 18 57@2x" src="https://user-images.githubusercontent.com/510177/194748643-1cca947d-754a-406a-affb-c2430c436456.png">

<img width="1302" alt="CleanShot 2022-10-09 at 11 19 24@2x" src="https://user-images.githubusercontent.com/510177/194748663-1026cc44-f3c6-45fe-9359-2a83bf57b73d.png">

<img width="1310" alt="CleanShot 2022-10-09 at 11 20 42@2x" src="https://user-images.githubusercontent.com/510177/194748712-b3a94c56-e22e-4f2a-a043-c8675698769a.png">

This has not occurred with clips so far.

I'm using the Go backend with commit 90d4c3ebe4d2563dd9eefd813a67e86f968ed217

Any idea what is happening here?

**Comment by seriousm4x** [comment]
Has not happened to me yet. Maybe one of them is a normal vod and the other one a twitch highlight? So they have different Twitch IDs

**Comment by Clasko** [comment]
I will try again with a clean DB. Thanks for your feedback. :)

**Comment by Clasko** [comment]
Still happens:
![CleanShot 2022-10-23 at 16 35 34](https://user-images.githubusercontent.com/510177/197398128-cc85756a-8180-4656-bebb-1836a356364f.png)

Clips are OK again

**Comment by seriousm4x** [comment]
I was able to reproduce it by lowering the interval for vod downloads to 1 minute (from 1h).

![Screenshot from 2022-10-23 23-58-03](https://user-images.githubusercontent.com/23456686/197420282-fcde3967-23ae-4d28-862c-e8ec6e7ca974.png)
![Screenshot from 2022-10-23 23-58-12](https://user-images.githubusercontent.com/23456686/197420284-c04acda5-e986-4b91-b096-3aa7270de4e1.png)

The problem was, that the first cronjob was still running while the second one (1 hour later) was triggered. This lead to multiple jobs running at the same time. So thats why the vod wasn't in the db yet and it started a second download.

I added a variable to check if the job is still running. If so, wait for the next interval in 1h and try again.

![Screenshot from 2022-10-24 00-04-08](https://user-images.githubusercontent.com/23456686/197420319-d0720985-6bb2-406b-964d-874c97573d57.png)

Let me know if that works for you. If not, feel free to reopen.
